---
title: "Test Intervention"
output: html_document
---

```{R Libraries}
suppressWarnings(suppressMessages(library(gdata)))
suppressMessages(suppressMessages(library(tibble)))
```

```{r actual model}
# define MAPK model
dE1 <- function(...) {
  0
}

dPRaf <- function(raf_activate, PRaf, E1, raf_deactivate, TRaf = 100, ...) {
  raf_activate * (TRaf-PRaf) * E1 - raf_deactivate * PRaf
}

dPPMek <- function(mek_activate, mek_deactivate, PRaf, PPMek, TMek = 100, ...) {
  (mek_activate ^ 2) * (PRaf ^ 2) * (TMek - PPMek) / mek_deactivate -       mek_activate * PRaf * PPMek -
    mek_deactivate * PPMek
}

dPPErk <- function(erk_activate, erk_deactivate, PPMek, PPErk, TErk = 100, ...) {
  (erk_activate ^ 2) * (PPMek ^ 2) * (TErk - PPErk) / erk_deactivate -      erk_activate * PPMek * PPErk -
    erk_deactivate * PPErk
}

# define initial rates
rates <- list(
  raf_activate = 0.1,
  raf_deactivate = 0.1,
  mek_activate = 0.1,
  mek_deactivate = 2.0,
  erk_activate = 0.1,
  erk_deactivate = 1.0
)

# so I guess we don't need Raf, Mek, PMek, Erk and PErk values!
initial_states <- list(
  E1 = 1,
  PRaf = 0,
  PPMek = 0,
  PPErk = 0
)

times <- seq(0, 120, by = .1)
```


```{R prototype of meta model}

meta_model <- function(list_of_models, list_of_ds, rates, states, interventions = NULL) {
  innerRates <- rates
  innerStates <- states
  innerIntervention <- interventions
      
  # update states with interventions 
  if(!is.null(interventions)) {
    for(int in names(interventions)){
      innerStates[[int]] <- interventions[[int]]
    }
  }
  
  # print(innerStates)
  
  transition_function <- function(t, states = innerStates, rates = innerRates, interventions = innerIntervention) {
  # check that list_of_models and list_of_ds are of the same length
  # throw an error if otherwise
    if (length(list_of_models) != length(list_of_ds)) 
      stop("Number of functions do not match nubmer of deltas. Check your input.") 
    
    # update states with interventions 
    if(!is.null(interventions)) {
      for(int in names(interventions)){
        states[[int]] <- interventions[[int]]
      }
    }
    
    # calculate original d
    result <- list()
    var <- as.list(c(rates, states))
    for (i in list_of_models) {
      result <- c(result, (do.call(i, var)))
    }
    
    result <- structure(result, names=list_of_ds)
    
    # update intervention
    for (elem in names(interventions)) {
      result[[paste0("d", elem)]] <- 0
    }
    
    list(unlist(result))  
  }
  
  
  attr(transition_function, 'rates') <- as.list(rates)
  attr(transition_function, 'states') <- as.list(states)
  attr(transition_function, 'interventions') <- as.list(interventions)
  # print(innerStates)
  return(transition_function)
}
```


```{R simulation}
ode_sim_meta_model <- function(meta_model_object, initial_states, times, interventions = NULL) {
  # interventions <- attr(meta_model_object, "interventions")
  # update states with interventions 
  if(!is.null(interventions)) {
    for(int in names(interventions)){
      initial_states[[int]] <- interventions[[int]]
    }
  }
  initial_states <- structure(as.numeric(initial_states), names = names(initial_states))
  # print(initial_states)
  rates <- attr(meta_model_object, 'rates')
  rates <- structure(as.numeric(rates), names = names(rates))
  rates <- as.list(rates)
  as_tibble(
    as.data.frame(
      deSolve::ode(
        y = initial_states,
        times = times,
        func = meta_model_object,
        parms = rates
      )
    )
  )
}
```

``` {R ode moment of truth}
#before intervention
test_bi <- meta_model(c(dE1, dPRaf, dPPMek, dPPErk), c("dE1", "dPRaf", "dPPMek", "dPPErk"), rates, initial_states)
test_bi()
ode_out_meta_model_bi <- ode_sim_meta_model(test_bi, initial_states, times)

#after intervention
intervention_PRaf_PPMek <- list(PPMek = 40, PRaf = 30)
test_ai_PRaf_PPMek <- meta_model(c(dE1, dPRaf, dPPMek, dPPErk), c("dE1", "dPRaf", "dPPMek", "dPPErk"), rates, initial_states, interventions = intervention_PRaf_PPMek)
ode_out_meta_model_ai_PRaf_PPMek <- ode_sim_meta_model(test_ai_PRaf_PPMek, initial_states, times, interventions = intervention_PRaf_PPMek)
```





```{r equilibrium}
library(gdata)

# need to modify for interventions: in case of intervention, do not calculate the equilibrium value? 
mapk_ode_equilM <- function(states, rates, TRaf, TMek, TErk, interventions = NULL) {
  innerState <- states
  innerRate <- rates
  transition_f <- function(states = innerState, rates = innerRate) {

    with(as.list(c(states, rates)), {
      w3 <- raf_activate/raf_deactivate
      w2 <- mek_activate/mek_deactivate
      w1 <- erk_activate/erk_deactivate
      
      t3 <- TRaf
      t2 <- TMek
      t1 <- TErk
      
      if(!is.null(interventions$PRaf)) {
        k3 <- interventions$PRaf
      } else {
        u3 <- w3 * E1
        k3 <- t3 * (u3/(1+u3))      
      }
      
      if(!is.null(interventions$PPMek)) {
        k2 <- interventions$PPMek
      } else {
        u2 <- w2 * k3
        k2 <- t2 * ((u2^2)/(1 + u2 + u2^2))
      }
  
      if(!is.null(interventions$PPErk)) {
        k1 <- interventions$PPErk
      } else {
        u1 <- w1 * k2
        k1 <- t3 * ((u1^2)/(1 + u1 + u1^2))      
      }
  
      list("PRaf" = k3, "PPMek" = k2, "PPErk" = k1)
      
      })
    }
  return(transition_f)
  
}

#intervention <- list(PPErk = 30)
# do(equil(M,X=x))
#mapk_ode_equilM(states = initial_states, rates, TRaf = 100, TMek = 100, TErk = 100, intervention)()

# What is equil(do(M,X=x))? I think do(M,X=x) is test_ai. Is it right?
```
# Comparison between steady state and stochastic simulation without intervention

```{r}
g1 <- function(a) a / (1 + a )
g2 <- function(a) a^2 / (1 + a + a^2)

TRaf = 100
TMek = 100
TErk = 100

E1 <- initial_states$E1
Raf <- TRaf * g1(E1 * rates$raf_activate / rates$raf_deactivate)
Mek <- TMek * g2(Raf * rates$mek_activate / rates$mek_deactivate)
Erk <- TErk * g2(Mek * rates$erk_activate / rates$erk_deactivate)

steady_states <- list(Raf=Raf, Mek=Mek, Erk=Erk)
```

The trajectories (solid lines) represent the evolution of the amounts of MAP3K (green), MAP2K (blue), and MAPK (red) in time. The dashed lines are the calculated equilibrium values.


```{r}
{plot(times, ode_out_meta_model_bi$PRaf, type='l', col='darkgreen', ylim=c(0, 110), ylab = 'amount')
lines(ode_out_meta_model_bi$PPMek, type='l', col='darkblue', ylim=c(0, 110))
lines(ode_out_meta_model_bi$PPErk, type='l', col='darkred', ylim=c(0, 110))
abline(h = Raf, col='darkgreen', lty=2)
abline(h = Mek, col='darkblue', lty=2)
abline(h = Erk, col='darkred', lty=2)}
```


## Comparison between $\text{equil}(\text{do}(\mathbb{M}, X = x))$ and $\text{do}(\text{equil}(\mathbb{M}, X = x))$
```{r}
# intervene on PRaf
# equil(do(M, X=x))
intervention_PRaf <- list(PRaf = 30)
test_ai_PRaf <- meta_model(c(dE1, dPRaf, dPPMek, dPPErk), c("dE1", "dPRaf", "dPPMek", "dPPErk"), rates, initial_states, interventions = intervention_PRaf)

ode_out_meta_model_ai_PRaf <- ode_sim_meta_model(test_ai_PRaf, initial_states, times, interventions = intervention_PRaf)

# do(equil(M, X = x))
do_equil_M_PRaf <- mapk_ode_equilM(states = initial_states, rates, TRaf = 100, TMek = 100, TErk = 100, intervention_PRaf)()


{plot(times, ode_out_meta_model_ai_PRaf$PRaf, type='l', col='darkgreen', ylim=c(0, 110), ylab = 'amount')
lines(ode_out_meta_model_ai_PRaf$PPMek, type='l', col='darkblue', ylim=c(0, 110))
lines(ode_out_meta_model_ai_PRaf$PPErk, type='l', col='darkred', ylim=c(0, 110))
abline(h = do_equil_M_PRaf$PRaf, col='darkgreen', lty=2)
abline(h = do_equil_M_PRaf$PPMek, col='darkblue', lty=2)
abline(h = do_equil_M_PRaf$PPErk, col='darkred', lty=2)
}
```

```{r}
# intervene on PPMek
# equil(do(M, X=x))
intervention_PPMek <- list(PPMek = 40)
test_ai_PPMek <- meta_model(c(dE1, dPRaf, dPPMek, dPPErk), c("dE1", "dPRaf", "dPPMek", "dPPErk"), rates, initial_states, interventions = intervention_PPMek)

ode_out_meta_model_ai_PPMek <- ode_sim_meta_model(test_ai_PPMek, initial_states, times, interventions = intervention_PPMek)

# do(equil(M, X = x))
do_equil_M_PPMek <- mapk_ode_equilM(states = initial_states, rates, TRaf = 100, TMek = 100, TErk = 100, intervention_PPMek)()


{plot(times, ode_out_meta_model_ai_PPMek$PRaf, type='l', col='darkgreen', ylim=c(0, 110), ylab = 'amount')
lines(ode_out_meta_model_ai_PPMek$PPMek, type='l', col='darkblue', ylim=c(0, 110))
lines(ode_out_meta_model_ai_PPMek$PPErk, type='l', col='darkred', ylim=c(0, 110))
abline(h = do_equil_M_PPMek$PRaf, col='darkgreen', lty=2)
abline(h = do_equil_M_PPMek$PPMek, col='darkblue', lty=2)
abline(h = do_equil_M_PPMek$PPErk, col='darkred', lty=2)
}
```


```{r}
# intervene on PPErk -> doesn't hold!
# equil(do(M, X=x))
intervention_PPErk <- list(PPErk = 60)
test_ai_PPErk <- meta_model(c(dE1, dPRaf, dPPMek, dPPErk), c("dE1", "dPRaf", "dPPMek", "dPPErk"), rates, initial_states, interventions = intervention_PPErk)

ode_out_meta_model_ai_PPErk <- ode_sim_meta_model(test_ai_PPErk, initial_states, times, interventions = intervention_PPErk)

# do(equil(M, X = x))
do_equil_M_PPErk <- mapk_ode_equilM(states = initial_states, rates, TRaf = 100, TMek = 100, TErk = 100, intervention_PPErk)()


{plot(times, ode_out_meta_model_ai_PPErk$PRaf, type='l', col='darkgreen', ylim=c(0, 110), ylab = 'amount')
lines(ode_out_meta_model_ai_PPErk$PPMek, type='l', col='darkblue', ylim=c(0, 110))
lines(ode_out_meta_model_ai_PPErk$PPErk, type='l', col='darkred', ylim=c(0, 110))
abline(h = do_equil_M_PPErk$PRaf, col='darkgreen', lty=2)
abline(h = do_equil_M_PPErk$PPMek, col='darkblue', lty=2)
abline(h = do_equil_M_PPErk$PPErk, col='darkred', lty=2)
}
```

```{r}
# intervene on PRaf and PPMek
# calculate do(equil(M, X = x))

intervention_PRaf_PPMek <- list(PPMek = 40, PRaf = 30)
test_ai_PRaf_PPMek <- meta_model(c(dE1, dPRaf, dPPMek, dPPErk), c("dE1", "dPRaf", "dPPMek", "dPPErk"), rates, initial_states, interventions = intervention_PRaf_PPMek)
ode_out_meta_model_ai_PRaf_PPMek <- ode_sim_meta_model(test_ai_PRaf_PPMek, initial_states, times, interventions = intervention_PRaf_PPMek)

do_equil_M_PPMek_PRaf <- mapk_ode_equilM(states = initial_states, rates, TRaf = 100, TMek = 100, TErk = 100, intervention_PRaf_PPMek)()


{plot(times, ode_out_meta_model_ai_PRaf_PPMek$PRaf, type='l', col='darkgreen', ylim=c(0, 110), ylab = 'amount')
lines(ode_out_meta_model_ai_PRaf_PPMek$PPMek, type='l', col='darkblue', ylim=c(0, 110))
lines(ode_out_meta_model_ai_PRaf_PPMek$PPErk, type='l', col='darkred', ylim=c(0, 110))
abline(h = do_equil_M_PPMek_PRaf$PRaf, col='darkgreen', lty=2)
abline(h = do_equil_M_PPMek_PRaf$PPMek, col='darkblue', lty=2)
abline(h = do_equil_M_PPMek_PRaf$PPErk, col='darkred', lty=2)
}
```


```{r}
# intervene on PRaf and PPErk
# equil(do(M, X=x))
intervention_PRaf_PPErk <- list(PRaf = 30, PPErk = 50)
test_ai_PRaf_PPErk <- meta_model(c(dE1, dPRaf, dPPMek, dPPErk), c("dE1", "dPRaf", "dPPMek", "dPPErk"), rates, initial_states, interventions = intervention_PRaf_PPErk)

ode_out_meta_model_ai_PRaf_PPErk <- ode_sim_meta_model(test_ai_PRaf_PPErk, initial_states, times, interventions = intervention_PRaf_PPErk)

# do(equil(M, X = x))
do_equil_M_PRaf_PPErk <- mapk_ode_equilM(states = initial_states, rates, TRaf = 100, TMek = 100, TErk = 100, intervention_PRaf_PPErk)()


{plot(times, ode_out_meta_model_ai_PRaf_PPErk$PRaf, type='l', col='darkgreen', ylim=c(0, 110), ylab = 'amount')
lines(ode_out_meta_model_ai_PRaf_PPErk$PPMek, type='l', col='darkblue', ylim=c(0, 110))
lines(ode_out_meta_model_ai_PRaf_PPErk$PPErk, type='l', col='darkred', ylim=c(0, 110))
abline(h = do_equil_M_PRaf_PPErk$PRaf, col='darkgreen', lty=2)
abline(h = do_equil_M_PRaf_PPErk$PPMek, col='darkblue', lty=2)
abline(h = do_equil_M_PRaf_PPErk$PPErk, col='darkred', lty=2)
}
```


```{r}
# intervene on PPMek and PPErk
# equil(do(M, X=x))
intervention_PPMek_PPErk <- list(PPMek = 30, PPErk = 40)
test_ai_PPMek_PPErk <- meta_model(c(dE1, dPRaf, dPPMek, dPPErk), c("dE1", "dPRaf", "dPPMek", "dPPErk"), rates, initial_states, interventions = intervention_PPMek_PPErk)

ode_out_meta_model_ai_PPMek_PPErk <- ode_sim_meta_model(test_ai_PPMek_PPErk, initial_states, times, interventions = intervention_PPMek_PPErk)

# do(equil(M, X = x))
do_equil_M_PPMek_PPErk <- mapk_ode_equilM(states = initial_states, rates, TRaf = 100, TMek = 100, TErk = 100, intervention_PPMek_PPErk)()


{plot(times, ode_out_meta_model_ai_PPMek_PPErk$PRaf, type='l', col='darkgreen', ylim=c(0, 110), ylab = 'amount')
lines(ode_out_meta_model_ai_PPMek_PPErk$PPMek, type='l', col='darkblue', ylim=c(0, 110))
lines(ode_out_meta_model_ai_PPMek_PPErk$PPErk, type='l', col='darkred', ylim=c(0, 110))
abline(h = do_equil_M_PPMek_PPErk$PRaf, col='darkgreen', lty=2)
abline(h = do_equil_M_PPMek_PPErk$PPMek, col='darkblue', lty=2)
abline(h = do_equil_M_PPMek_PPErk$PPErk, col='darkred', lty=2)
}
```

```{r echo=FALSE}
# intervene on PRaf, PPMek and PPErk b/c why not
# equil(do(M, X=x))
intervention_PRaf_PPMek_PPErk <- list(PRaf = 30, PPMek = 40, PPErk = 50)
test_ai_PRaf_PPMek_PPErk <- meta_model(c(dE1, dPRaf, dPPMek, dPPErk), c("dE1", "dPRaf", "dPPMek", "dPPErk"), rates, initial_states, interventions = intervention_PRaf_PPMek_PPErk)

ode_out_meta_model_ai_PRaf_PPMek_PPErk <- ode_sim_meta_model(test_ai_PRaf_PPMek_PPErk, initial_states, times, interventions = intervention_PRaf_PPErk)

# do(equil(M, X = x))
do_equil_M_PRaf_PPMek_PPErk <- mapk_ode_equilM(states = initial_states, rates, TRaf = 100, TMek = 100, TErk = 100, intervention_PRaf_PPMek_PPErk)()


{plot(times, ode_out_meta_model_ai_PRaf_PPMek_PPErk$PRaf, type='l', col='darkgreen', ylim=c(0, 110), ylab = 'amount')
lines(ode_out_meta_model_ai_PRaf_PPMek_PPErk$PPMek, type='l', col='darkblue', ylim=c(0, 110))
lines(ode_out_meta_model_ai_PRaf_PPMek_PPErk$PPErk, type='l', col='darkred', ylim=c(0, 110))
abline(h = do_equil_M_PRaf_PPMek_PPErk$PRaf, col='darkgreen', lty=2)
abline(h = do_equil_M_PRaf_PPMek_PPErk$PPMek, col='darkblue', lty=2)
abline(h = do_equil_M_PRaf_PPMek_PPErk$PPErk, col='darkred', lty=2)
}
```
